# Generated by Django 5.0.4 on 2024-06-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_respiratorydetection_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respiratorydetection',
            name='doctor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
